<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.357">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>git_commit_graph_ext - Large Git repositories</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="git_commit_graph_ext - Large Git repositories">
<meta property="og:description" content="">
<meta property="og:image" content="https://jnareb.github.io/git-commit-graph-ext/12_repos_files/figure-html/cell-78-output-1.png">
<meta property="og:site-name" content="git_commit_graph_ext">
<meta property="og:image:height" content="609">
<meta property="og:image:width" content="1059">
<meta name="twitter:title" content="git_commit_graph_ext - Large Git repositories">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://jnareb.github.io/git-commit-graph-ext/12_repos_files/figure-html/cell-78-output-1.png">
<meta name="twitter:image-height" content="609">
<meta name="twitter:image-width" content="1059">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">git_commit_graph_ext</span>
    </a>
  </div>
        <div class="quarto-navbar-tools ms-auto">
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./repos.html">Large Git repositories</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Commit graph labeling for speeding up Git commands</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Graphs in Python</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./related.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Related works: various reachability labelings</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example_graphs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Example directed graphs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reachability_index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reachability index</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./levels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Topological levels</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interval_labels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DFS Intervals Labelling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reach.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reachability queries</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./git.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extracting commit graphs from Git repositories</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./checkpoint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Checkpointing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Graph datasets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./repos.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Large Git repositories</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reachability evaluation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a.09_git_explore.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploring extraction of commit graphs from Git repositories, and examining their shape and stats</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#from-gen-test-repository" id="toc-from-gen-test-repository" class="nav-link active" data-scroll-target="#from-gen-test-repository">From <code>gen-test</code> repository</a>
  <ul class="collapse">
  <li><a href="#curl-repository" id="toc-curl-repository" class="nav-link" data-scroll-target="#curl-repository">cURL repository</a></li>
  <li><a href="#electron-repository" id="toc-electron-repository" class="nav-link" data-scroll-target="#electron-repository">Electron repository</a></li>
  <li><a href="#ffmpeg-repository" id="toc-ffmpeg-repository" class="nav-link" data-scroll-target="#ffmpeg-repository">FFmpeg repository</a></li>
  <li><a href="#jgit-repository" id="toc-jgit-repository" class="nav-link" data-scroll-target="#jgit-repository">JGit repository</a></li>
  <li><a href="#the-julia-language-repository" id="toc-the-julia-language-repository" class="nav-link" data-scroll-target="#the-julia-language-repository">The Julia language repository</a></li>
  <li><a href="#the-kotlin-language-repository" id="toc-the-kotlin-language-repository" class="nav-link" data-scroll-target="#the-kotlin-language-repository">The Kotlin language repository</a></li>
  <li><a href="#linux-repository" id="toc-linux-repository" class="nav-link" data-scroll-target="#linux-repository">Linux repository</a></li>
  <li><a href="#odoo-repository" id="toc-odoo-repository" class="nav-link" data-scroll-target="#odoo-repository">Odoo repository</a></li>
  <li><a href="#openssl-repository" id="toc-openssl-repository" class="nav-link" data-scroll-target="#openssl-repository">OpenSSL repository</a></li>
  <li><a href="#the-swift-language-repository" id="toc-the-swift-language-repository" class="nav-link" data-scroll-target="#the-swift-language-repository">The Swift language repository</a></li>
  <li><a href="#tensorflow-repository" id="toc-tensorflow-repository" class="nav-link" data-scroll-target="#tensorflow-repository">TensorFlow repository</a></li>
  <li><a href="#the-typescript-language-repository" id="toc-the-typescript-language-repository" class="nav-link" data-scroll-target="#the-typescript-language-repository">The TypeScript language repository</a></li>
  <li><a href="#git-project-repository" id="toc-git-project-repository" class="nav-link" data-scroll-target="#git-project-repository">Git project repository</a></li>
  <li><a href="#gerrit-repository" id="toc-gerrit-repository" class="nav-link" data-scroll-target="#gerrit-repository">Gerrit repository</a></li>
  <li><a href="#android-base-repository" id="toc-android-base-repository" class="nav-link" data-scroll-target="#android-base-repository">Android-base repository</a></li>
  <li><a href="#chromium-repository" id="toc-chromium-repository" class="nav-link" data-scroll-target="#chromium-repository">Chromium repository</a></li>
  </ul></li>
  <li><a href="#slides-unused-repositories" id="toc-slides-unused-repositories" class="nav-link" data-scroll-target="#slides-unused-repositories">Slides (unused repositories)</a>
  <ul class="collapse">
  <li><a href="#llvm-repository" id="toc-llvm-repository" class="nav-link" data-scroll-target="#llvm-repository">LLVM repository</a></li>
  <li><a href="#gcc-repository" id="toc-gcc-repository" class="nav-link" data-scroll-target="#gcc-repository">GCC repository</a></li>
  <li><a href="#homebrew-repository" id="toc-homebrew-repository" class="nav-link" data-scroll-target="#homebrew-repository">Homebrew repository</a></li>
  <li><a href="#ruby-on-rails-repository" id="toc-ruby-on-rails-repository" class="nav-link" data-scroll-target="#ruby-on-rails-repository">Ruby on Rails repository</a></li>
  </ul></li>
  <li><a href="#github-blog-post-on-cloning-behavior" id="toc-github-blog-post-on-cloning-behavior" class="nav-link" data-scroll-target="#github-blog-post-on-cloning-behavior">GitHub Blog post on cloning behavior</a>
  <ul class="collapse">
  <li><a href="#jquery-repository" id="toc-jquery-repository" class="nav-link" data-scroll-target="#jquery-repository">jQuery repository</a></li>
  </ul></li>
  <li><a href="#other-possibilities" id="toc-other-possibilities" class="nav-link" data-scroll-target="#other-possibilities">Other possibilities</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/jnareb/git-commit-graph-ext/tree/master/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Large Git repositories</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->
<p>Imports for handling graphs in Python</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> networkx <span class="im">as</span> nx</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Imports for cloning Git repositories and extracting the commit graph</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> git_commit_graph_ext.commit_graph <span class="im">import</span> commit_graph, _repo_graph_name</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Gathering cloned repositories and their graphs</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>known_repos <span class="op">=</span> []</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This should perhaps be a list of objects of specific defined type, not list of dicts</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_known_repos():</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> known_repos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>get_known_repos()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>[]</code></pre>
</div>
</div>
<section id="from-gen-test-repository" class="level2">
<h2 class="anchored" data-anchor-id="from-gen-test-repository">From <code>gen-test</code> repository</h2>
<p><a href="https://github.com/derrickstolee/gen-test">gen-test</a> – Test scripts for testing new versions of generation numbers.</p>
<p>From the README:</p>
<blockquote class="blockquote">
<p>This report investigates four replacements for generation numbers, and compares the number of walked commits to the existing algorithms (both using generation numbers and not using them at all). We can use this data to make decisions for the future of the feature.</p>
</blockquote>
<p>https://github.com/derrickstolee/gen-test/blob/master/clone-repos.sh</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone git@github.com:derrickstolee/git.git <span class="at">--branch</span> reach-perf</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone git@github.com:curl/curl</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone git@github.com:electron/electron</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone git@github.com:FFmpeg/FFmpeg</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone git@github.com:eclipse/jgit</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone git@github.com:JuliaLang/julia</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone git@github.com:jetbrains/kotlin</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone git@github.com:torvalds/linux</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone git@github.com:odoo/odoo</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone git@github.com:openssl/openssl</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone git@github.com:apple/swift</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone git@github.com:tensorflow/tensorflow</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone git@github.com:microsoft/TypeScript</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone https://gerrit.googlesource.com/gerrit</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone https://android.googlesource.com/platform/frameworks/base/ android-base</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone https://chromium.googlesource.com/chromium/src chromium</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>the repositoriess from googlesource.com have trouble with cloning; it might be better to clone them from command line, not from this Jupyter notebook.</p>
</div>
</div>
<section id="curl-repository" class="level3">
<h3 class="anchored" data-anchor-id="curl-repository">cURL repository</h3>
<p>Curl is a command-line tool for transferring data specified with URL syntax.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>curl_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/curl/curl.git'</span>, <span class="st">'curl'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 289 ms</code></pre>
</div>
</div>
<p>It takes around 9 s to reclone the <code>curl</code> repository, 4 s to rescan it, and 300 ms to refresh it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>known_repos <span class="op">=</span> []</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>known_repos.append(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>        <span class="st">'name'</span>: <span class="st">'curl'</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">'url'</span>: <span class="st">'https://github.com/curl/curl'</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">'graph'</span>: curl_graph,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>known_repos[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>{'name': 'curl',
 'url': 'https://github.com/curl/curl',
 'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3ca0&gt;}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has'</span>.<span class="bu">format</span>(known_repos[<span class="dv">0</span>][<span class="st">'name'</span>]))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repos[<span class="dv">0</span>][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repos[<span class="dv">0</span>][<span class="st">'graph'</span>].number_of_edges()))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.5f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repos[<span class="dv">0</span>][<span class="st">'graph'</span>].number_of_edges() <span class="op">/</span> known_repos[<span class="dv">0</span>][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repos[<span class="dv">0</span>][<span class="st">'graph'</span>] <span class="cf">if</span> known_repos[<span class="dv">0</span>][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repos[<span class="dv">0</span>][<span class="st">'graph'</span>] <span class="cf">if</span> known_repos[<span class="dv">0</span>][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "curl" project has
- 26609 nodes / vertices / commits
- 26631 edges
- 1.00083 edge density, number of edges divided by number of nodes (vertices)
- 1 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 14 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
</section>
<section id="electron-repository" class="level3">
<h3 class="anchored" data-anchor-id="electron-repository">Electron repository</h3>
<p>Electron – Build cross-platform desktop apps with JavaScript, HTML, and CSS</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>electron_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/electron/electron.git'</span>, <span class="st">'electron'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 553 ms</code></pre>
</div>
</div>
<p>It takes around 15 seconds to clone the Electron repository, and construct it’s commit graph as NetworkX.DiGraph</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>known_repos.append({</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'electron'</span>,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/electron/electron.git'</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: electron_graph,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>known_repos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>[{'name': 'curl',
  'url': 'https://github.com/curl/curl',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3ca0&gt;},
 {'name': 'electron',
  'url': 'https://github.com/electron/electron.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3970&gt;}]</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has'</span>.<span class="bu">format</span>(known_repos[<span class="dv">1</span>][<span class="st">'name'</span>]))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repos[<span class="dv">1</span>][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repos[<span class="dv">1</span>][<span class="st">'graph'</span>].number_of_edges()))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.5f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repos[<span class="dv">1</span>][<span class="st">'graph'</span>].number_of_edges() <span class="op">/</span> known_repos[<span class="dv">1</span>][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repos[<span class="dv">1</span>][<span class="st">'graph'</span>] <span class="cf">if</span> known_repos[<span class="dv">1</span>][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repos[<span class="dv">1</span>][<span class="st">'graph'</span>] <span class="cf">if</span> known_repos[<span class="dv">1</span>][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "electron" project has
- 29956 nodes / vertices / commits
- 34167 edges
- 1.14057 edge density, number of edges divided by number of nodes (vertices)
- 4 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 142 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
</section>
<section id="ffmpeg-repository" class="level3">
<h3 class="anchored" data-anchor-id="ffmpeg-repository">FFmpeg repository</h3>
<p><a href="https://github.com/FFmpeg/FFmpeg" class="uri">https://github.com/FFmpeg/FFmpeg</a> is a mirror of <a href="https://git.ffmpeg.org/ffmpeg.git" class="uri">https://git.ffmpeg.org/ffmpeg.git</a></p>
<p>FFmpeg is a collection of libraries and tools to process multimedia content such as audio, video, subtitles and related metadata.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>ffmpeg_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/FFmpeg/FFmpeg.git'</span>, <span class="st">'ffmpeg'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 2.14 s</code></pre>
</div>
</div>
<p>It takes around 14 seconds to clone the FFmpeg repository, and construct it’s commit graph as NetworkX.DiGraph,<br>
and around 1.4 seconds to refresh it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>known_repos.append({</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'ffmpeg'</span>,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/FFmpeg/FFmpeg.git'</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: ffmpeg_graph</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>known_repos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>[{'name': 'curl',
  'url': 'https://github.com/curl/curl',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3ca0&gt;},
 {'name': 'electron',
  'url': 'https://github.com/electron/electron.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3970&gt;},
 {'name': 'ffmpeg',
  'url': 'https://github.com/FFmpeg/FFmpeg.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3ee0&gt;}]</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>graph_idx <span class="op">=</span> <span class="dv">2</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph [</span><span class="sc">{}</span><span class="st">] of "</span><span class="sc">{}</span><span class="st">" project has'</span>.<span class="bu">format</span>(graph_idx, known_repos[graph_idx][<span class="st">'name'</span>]))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repos[graph_idx][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repos[graph_idx][<span class="st">'graph'</span>].number_of_edges()))</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.5f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repos[graph_idx][<span class="st">'graph'</span>].number_of_edges() <span class="op">/</span> known_repos[graph_idx][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repos[graph_idx][<span class="st">'graph'</span>] <span class="cf">if</span> known_repos[graph_idx][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repos[graph_idx][<span class="st">'graph'</span>] <span class="cf">if</span> known_repos[graph_idx][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph [2] of "ffmpeg" project has
- 120583 nodes / vertices / commits
- 130606 edges
- 1.08312 edge density, number of edges divided by number of nodes (vertices)
- 1 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 30 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
</section>
<section id="jgit-repository" class="level3">
<h3 class="anchored" data-anchor-id="jgit-repository">JGit repository</h3>
<p>JGit - An implementation of the Git version control system in pure Java</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>jgit_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/eclipse/jgit.git'</span>, <span class="st">'jgit'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 195 ms</code></pre>
</div>
</div>
<p>It takes around 34 seconds to clone the JGit repository, and construct it’s commit graph as NetworkX.DiGraph,<br>
and 70 ms to refresh it</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#known_repos[3] = {</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>known_repos.append({</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'jgit'</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/eclipse/jgit.git'</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: jgit_graph</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>known_repos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>[{'name': 'curl',
  'url': 'https://github.com/curl/curl',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3ca0&gt;},
 {'name': 'electron',
  'url': 'https://github.com/electron/electron.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3970&gt;},
 {'name': 'ffmpeg',
  'url': 'https://github.com/FFmpeg/FFmpeg.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3ee0&gt;},
 {'name': 'jgit',
  'url': 'https://github.com/eclipse/jgit.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e79ea4f0&gt;}]</code></pre>
</div>
</div>
<p>On 01.01.2021 the JGit project had 8,162 commits, according to GitHub web UI</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>graph_idx <span class="op">=</span> <span class="dv">3</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph [</span><span class="sc">{}</span><span class="st">] of "</span><span class="sc">{}</span><span class="st">" project has'</span>.<span class="bu">format</span>(graph_idx, known_repos[graph_idx][<span class="st">'name'</span>]))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repos[graph_idx][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repos[graph_idx][<span class="st">'graph'</span>].number_of_edges()))</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.5f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repos[graph_idx][<span class="st">'graph'</span>].number_of_edges() <span class="op">/</span> known_repos[graph_idx][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repos[graph_idx][<span class="st">'graph'</span>] <span class="cf">if</span> known_repos[graph_idx][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repos[graph_idx][<span class="st">'graph'</span>] <span class="cf">if</span> known_repos[graph_idx][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph [3] of "jgit" project has
- 8173 nodes / vertices / commits
- 9853 edges
- 1.20555 edge density, number of edges divided by number of nodes (vertices)
- 1 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 2 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
</section>
<section id="the-julia-language-repository" class="level3">
<h3 class="anchored" data-anchor-id="the-julia-language-repository">The Julia language repository</h3>
<p>The Julia Programming Language<br>
<a href="https://julialang.org/" class="uri">https://julialang.org/</a></p>
<p>Julia is a high-level, high-performance dynamic language for technical computing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>julia_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/JuliaLang/julia.git'</span>, <span class="st">'julia'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 1.38 s</code></pre>
</div>
</div>
<p>It takes around 32.7 seconds to run <code>commit_graph()</code> from scratch</p>
<p>The Julia language repository had 48,658 commits on 01.01.2021</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>known_repos.append({</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'julia'</span>,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/JuliaLang/julia.git'</span>,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'homepage'</span>: <span class="st">'https://julialang.org'</span>,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: julia_graph</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>known_repos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>[{'name': 'curl',
  'url': 'https://github.com/curl/curl',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3ca0&gt;},
 {'name': 'electron',
  'url': 'https://github.com/electron/electron.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3970&gt;},
 {'name': 'ffmpeg',
  'url': 'https://github.com/FFmpeg/FFmpeg.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3ee0&gt;},
 {'name': 'jgit',
  'url': 'https://github.com/eclipse/jgit.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e79ea4f0&gt;},
 {'name': 'julia',
  'url': 'https://github.com/JuliaLang/julia.git',
  'homepage': 'https://julialang.org',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195f34bdc40&gt;}]</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>graph_idx <span class="op">=</span> <span class="dv">4</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph [</span><span class="sc">{}</span><span class="st">] of "</span><span class="sc">{}</span><span class="st">" project has'</span>.<span class="bu">format</span>(graph_idx, known_repos[graph_idx][<span class="st">'name'</span>]))</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repos[graph_idx][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repos[graph_idx][<span class="st">'graph'</span>].number_of_edges()))</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.5f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repos[graph_idx][<span class="st">'graph'</span>].number_of_edges() <span class="op">/</span> known_repos[graph_idx][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repos[graph_idx][<span class="st">'graph'</span>] <span class="cf">if</span> known_repos[graph_idx][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repos[graph_idx][<span class="st">'graph'</span>] <span class="cf">if</span> known_repos[graph_idx][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph [4] of "julia" project has
- 56048 nodes / vertices / commits
- 67547 edges
- 1.20516 edge density, number of edges divided by number of nodes (vertices)
- 5 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 869 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
</section>
<section id="the-kotlin-language-repository" class="level3">
<h3 class="anchored" data-anchor-id="the-kotlin-language-repository">The Kotlin language repository</h3>
<p>The Kotlin Programming Language<br>
https://kotlinlang.org/</p>
<p><strong>Kotlin</strong> is an open-source, statically typed programming language supported and developed by JetBrains and open-source contributors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>kotlin_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/JetBrains/kotlin.git'</span>, <span class="st">'kotlin'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 2.74 s</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>known_repos.append({</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/JetBrains/kotlin.git'</span>,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'kotlin'</span>,</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'homepage'</span>: <span class="st">'https://kotlinlang.org/'</span>,</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: kotlin_graph,</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>known_repos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>[{'name': 'curl',
  'url': 'https://github.com/curl/curl',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3ca0&gt;},
 {'name': 'electron',
  'url': 'https://github.com/electron/electron.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3970&gt;},
 {'name': 'ffmpeg',
  'url': 'https://github.com/FFmpeg/FFmpeg.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3ee0&gt;},
 {'name': 'jgit',
  'url': 'https://github.com/eclipse/jgit.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e79ea4f0&gt;},
 {'name': 'julia',
  'url': 'https://github.com/JuliaLang/julia.git',
  'homepage': 'https://julialang.org',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195f34bdc40&gt;},
 {'url': 'https://github.com/JetBrains/kotlin.git',
  'name': 'kotlin',
  'homepage': 'https://kotlinlang.org/',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195f7f1a670&gt;}]</code></pre>
</div>
</div>
<p>GitHub repo @ 01.01.2021: 71,704 commits, 3,007 branches, 20,721 tags</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>graph_idx <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph [</span><span class="sc">{}</span><span class="st">] of "</span><span class="sc">{}</span><span class="st">" project has'</span>.<span class="bu">format</span>(graph_idx, known_repos[graph_idx][<span class="st">'name'</span>]))</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repos[graph_idx][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repos[graph_idx][<span class="st">'graph'</span>].number_of_edges()))</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.5f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repos[graph_idx][<span class="st">'graph'</span>].number_of_edges() <span class="op">/</span> known_repos[graph_idx][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repos[graph_idx][<span class="st">'graph'</span>] <span class="cf">if</span> known_repos[graph_idx][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repos[graph_idx][<span class="st">'graph'</span>] <span class="cf">if</span> known_repos[graph_idx][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph [5] of "kotlin" project has
- 117495 nodes / vertices / commits
- 119013 edges
- 1.01292 edge density, number of edges divided by number of nodes (vertices)
- 9 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 2592 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
</section>
<section id="linux-repository" class="level3">
<h3 class="anchored" data-anchor-id="linux-repository">Linux repository</h3>
<p>Linux kernel source tree (on GitHub)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>linux_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/torvalds/linux.git'</span>, <span class="st">'linux'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 16.9 s</code></pre>
</div>
</div>
<p>Wall time: 1min 44s (full clone and extracting the commit graph)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>known_repos.append({</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/torvalds/linux.git'</span>,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'linux'</span>,</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: linux_graph,</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>known_repos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>[{'name': 'curl',
  'url': 'https://github.com/curl/curl',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3ca0&gt;},
 {'name': 'electron',
  'url': 'https://github.com/electron/electron.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3970&gt;},
 {'name': 'ffmpeg',
  'url': 'https://github.com/FFmpeg/FFmpeg.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3ee0&gt;},
 {'name': 'jgit',
  'url': 'https://github.com/eclipse/jgit.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e79ea4f0&gt;},
 {'name': 'julia',
  'url': 'https://github.com/JuliaLang/julia.git',
  'homepage': 'https://julialang.org',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195f34bdc40&gt;},
 {'url': 'https://github.com/JetBrains/kotlin.git',
  'name': 'kotlin',
  'homepage': 'https://kotlinlang.org/',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195f7f1a670&gt;},
 {'url': 'https://github.com/torvalds/linux.git',
  'name': 'linux',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3550&gt;}]</code></pre>
</div>
</div>
<p>982,030 commits, 1 branch, 679 tags</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>graph_idx <span class="op">=</span> <span class="dv">6</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph [</span><span class="sc">{}</span><span class="st">] of "</span><span class="sc">{}</span><span class="st">" project has'</span>.<span class="bu">format</span>(graph_idx, known_repos[graph_idx][<span class="st">'name'</span>]))</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repos[graph_idx][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repos[graph_idx][<span class="st">'graph'</span>].number_of_edges()))</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.5f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repos[graph_idx][<span class="st">'graph'</span>].number_of_edges() <span class="op">/</span> known_repos[graph_idx][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repos[graph_idx][<span class="st">'graph'</span>] <span class="cf">if</span> known_repos[graph_idx][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repos[graph_idx][<span class="st">'graph'</span>] <span class="cf">if</span> known_repos[graph_idx][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph [6] of "linux" project has
- 982030 nodes / vertices / commits
- 1061095 edges
- 1.08051 edge density, number of edges divided by number of nodes (vertices)
- 4 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 1 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
</section>
<section id="odoo-repository" class="level3">
<h3 class="anchored" data-anchor-id="odoo-repository">Odoo repository</h3>
<p>Odoo. Open Source Apps To Grow Your Business.<br>
<a href="https://www.odoo.com/" class="uri">https://www.odoo.com/</a></p>
<p><strong>Odoo</strong> is a suite of web based open source business apps.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>odoo_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/odoo/odoo.git'</span>, <span class="st">'odoo'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 2.51 s</code></pre>
</div>
</div>
<p>Wall time 1min 4s (first time <code>commit_graph()</code>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>known_repo <span class="op">=</span> {repo[<span class="st">'name'</span>]: repo <span class="cf">for</span> repo <span class="kw">in</span> known_repos}</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>known_repo</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>{'curl': {'name': 'curl',
  'url': 'https://github.com/curl/curl',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3ca0&gt;},
 'electron': {'name': 'electron',
  'url': 'https://github.com/electron/electron.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3970&gt;},
 'ffmpeg': {'name': 'ffmpeg',
  'url': 'https://github.com/FFmpeg/FFmpeg.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3ee0&gt;},
 'jgit': {'name': 'jgit',
  'url': 'https://github.com/eclipse/jgit.git',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e79ea4f0&gt;},
 'julia': {'name': 'julia',
  'url': 'https://github.com/JuliaLang/julia.git',
  'homepage': 'https://julialang.org',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195f34bdc40&gt;},
 'kotlin': {'url': 'https://github.com/JetBrains/kotlin.git',
  'name': 'kotlin',
  'homepage': 'https://kotlinlang.org/',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195f7f1a670&gt;},
 'linux': {'url': 'https://github.com/torvalds/linux.git',
  'name': 'linux',
  'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e59d3550&gt;}}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'odoo'</span>] <span class="op">=</span> {</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'odoo'</span>,</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/odoo/odoo.git'</span>,</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'homepage'</span>: <span class="st">'https://www.odoo.com/'</span>,</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: odoo_graph,</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'odoo'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>{'name': 'odoo',
 'url': 'https://github.com/odoo/odoo.git',
 'homepage': 'https://www.odoo.com/',
 'graph': &lt;networkx.classes.digraph.DiGraph at 0x195f34bd4c0&gt;}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>repo_name <span class="op">=</span> <span class="st">'odoo'</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has:'</span>.<span class="bu">format</span>(repo_name))</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'graph'</span>].number_of_edges()))</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.6f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repo[repo_name][<span class="st">'graph'</span>].number_of_edges() <span class="op">/</span> known_repo[repo_name][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "odoo" project has:
- 158324 nodes / vertices / commits
- 184403 edges
- 1.164719 edge density, number of edges divided by number of nodes (vertices)
- 7 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 33 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
<p>On GitHub @ 01.01.2021: 139,989 commits, 82 branches, 0 tags</p>
</section>
<section id="openssl-repository" class="level3">
<h3 class="anchored" data-anchor-id="openssl-repository">OpenSSL repository</h3>
<p><strong>OpenSSL</strong> is a robust, commercial-grade, full-featured Open Source Toolkit for the Transport Layer Security (TLS) protocol formerly known as the Secure Sockets Layer (SSL) protocol. The protocol implementation is based on a full-strength general purpose cryptographic library, which can also be used stand-alone.</p>
<p>OpenSSL is descended from the SSLeay library developed by Eric A. Young and Tim J. Hudson.</p>
<p>The official Home Page of the OpenSSL Project is &lt;www.openssl.org&gt;.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>openssl_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/openssl/openssl.git'</span>, <span class="st">'openssl'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 763 ms</code></pre>
</div>
</div>
<p>Wall time 18 seconds (first time)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'openssl'</span>] <span class="op">=</span> {</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'openssl'</span>,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/openssl/openssl.git'</span>,</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'homepage'</span>: <span class="st">'https://www.openssl.org'</span>,</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: openssl_graph,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'openssl'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>{'name': 'openssl',
 'url': 'https://github.com/openssl/openssl.git',
 'homepage': 'https://www.openssl.org',
 'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e2d57430&gt;}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>repo_name <span class="op">=</span> <span class="st">'openssl'</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has:'</span>.<span class="bu">format</span>(repo_name))</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'graph'</span>].number_of_edges()))</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.6f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repo[repo_name][<span class="st">'graph'</span>].number_of_edges() <span class="op">/</span> known_repo[repo_name][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "openssl" project has:
- 42818 nodes / vertices / commits
- 42997 edges
- 1.004180 edge density, number of edges divided by number of nodes (vertices)
- 6 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 19 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
<p>OpenSSL repo @ 01.01.2021: 27,812 commits, 20 branches, 320 tags</p>
</section>
<section id="the-swift-language-repository" class="level3">
<h3 class="anchored" data-anchor-id="the-swift-language-repository">The Swift language repository</h3>
<p>The Swift Programming Language<br>
<a href="https://swift.org" class="uri">https://swift.org</a></p>
<p><strong>Swift</strong> is a high-performance system programming language. It has a clean and modern syntax, offers seamless access to existing C and Objective-C code and frameworks, and is memory safe by default.</p>
<p>Although inspired by Objective-C and many other languages, Swift is not itself a C-derived language. As a complete and independent language, Swift packages core features like flow control, data structures, and functions, with high-level constructs like objects, protocols, closures, and generics. Swift embraces modules, eliminating the need for headers and the code duplication they entail.</p>
<p>To learn more about the programming language, visit <a href="https://swift.org/documentation/">swift.org</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>swift_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/apple/swift.git'</span>, <span class="st">'swift'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 4.25 s</code></pre>
</div>
</div>
<p>Wall time: 41 s (first time)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'swift'</span>] <span class="op">=</span> {</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'swift'</span>,</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/apple/swift.git'</span>,</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'homepage'</span>: <span class="st">'https://swift.org'</span>,</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: swift_graph,</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_nodes'</span>: swift_graph.number_of_nodes(),</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_edges'</span>: swift_graph.number_of_edges(),</span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'swift'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>{'name': 'swift',
 'url': 'https://github.com/apple/swift.git',
 'homepage': 'https://swift.org',
 'graph': &lt;networkx.classes.digraph.DiGraph at 0x195f7f1a130&gt;,
 'n_nodes': 132444,
 'n_edges': 176028}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>repo_name <span class="op">=</span> <span class="st">'swift'</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has:'</span>.<span class="bu">format</span>(repo_name))</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'graph'</span>].number_of_edges()))</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.6f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repo[repo_name][<span class="st">'graph'</span>].number_of_edges() <span class="op">/</span> known_repo[repo_name][<span class="st">'graph'</span>].number_of_nodes()))</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "swift" project has:
- 132444 nodes / vertices / commits
- 176028 edges
- 1.329075 edge density, number of edges divided by number of nodes (vertices)
- 1 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 209 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
<p>Swift repository on GitHub @ 01.01.2021: 114,559 commits</p>
</section>
<section id="tensorflow-repository" class="level3">
<h3 class="anchored" data-anchor-id="tensorflow-repository">TensorFlow repository</h3>
<p>An Open Source Machine Learning Framework for Everyone<br>
https://tensorflow.org</p>
<p><strong>TensorFlow</strong> is an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries, and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML-powered applications.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>tensorflow_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/tensorflow/tensorflow.git'</span>, <span class="st">'tensorflow'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 2.12 s</code></pre>
</div>
</div>
<p>Wall time: 34.3 s (first time)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'tensorflow'</span>] <span class="op">=</span> {</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'tensorflow'</span>,</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/tensorflow/tensorflow.git'</span>,</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'homepage'</span>: <span class="st">'https://tensorflow.org'</span>,</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: tensorflow_graph,</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_nodes'</span>: tensorflow_graph.number_of_nodes(),</span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_edges'</span>: tensorflow_graph.number_of_edges(),</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'tensorflow'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>{'name': 'tensorflow',
 'url': 'https://github.com/tensorflow/tensorflow.git',
 'homepage': 'https://tensorflow.org',
 'graph': &lt;networkx.classes.digraph.DiGraph at 0x195e79ea340&gt;,
 'n_nodes': 105236,
 'n_edges': 115687}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>repo_name <span class="op">=</span> <span class="st">'tensorflow'</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has:'</span>.<span class="bu">format</span>(repo_name))</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>]))</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.6f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>] <span class="op">/</span> known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "tensorflow" project has:
- 105236 nodes / vertices / commits
- 115687 edges
- 1.099310 edge density, number of edges divided by number of nodes (vertices)
- 3 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 32 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
<p>TensorFlow repository on GitHub @ 01.01.2021: 102,131 commits, 36 branches</p>
</section>
<section id="the-typescript-language-repository" class="level3">
<h3 class="anchored" data-anchor-id="the-typescript-language-repository">The TypeScript language repository</h3>
<p>TypeScript is a superset of JavaScript that compiles to clean JavaScript output.<br>
www.typescriptlang.org</p>
<p><strong>TypeScript</strong> is a language for application-scale JavaScript. TypeScript adds optional types to JavaScript that support tools for large-scale JavaScript applications for any browser, for any host, on any OS. TypeScript compiles to readable, standards-based JavaScript.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>typescript_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/microsoft/TypeScript.git'</span>, <span class="st">'typescript'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 1.04 s</code></pre>
</div>
</div>
<p>Wall time: 23.4 s (first time)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'typescript'</span>] <span class="op">=</span> {</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'typescript'</span>,</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/microsoft/TypeScript.git'</span>,</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'homepage'</span>: <span class="st">'https://www.typescriptlang.org/'</span>,</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: typescript_graph,</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_nodes'</span>: typescript_graph.number_of_nodes(),</span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_edges'</span>: typescript_graph.number_of_edges(),</span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'typescript'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>{'name': 'typescript',
 'url': 'https://github.com/microsoft/TypeScript.git',
 'homepage': 'https://www.typescriptlang.org/',
 'graph': &lt;networkx.classes.digraph.DiGraph at 0x195f7f1ad90&gt;,
 'n_nodes': 35486,
 'n_edges': 43895}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>repo_name <span class="op">=</span> <span class="st">'typescript'</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has:'</span>.<span class="bu">format</span>(repo_name))</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>]))</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.6f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>] <span class="op">/</span> known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "typescript" project has:
- 35486 nodes / vertices / commits
- 43895 edges
- 1.236967 edge density, number of edges divided by number of nodes (vertices)
- 1 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 419 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
<p>TypeScript repository on GitHub @ 01.01.2021: 31,596 commits, 455 branches</p>
</section>
<section id="git-project-repository" class="level3">
<h3 class="anchored" data-anchor-id="git-project-repository">Git project repository</h3>
<p><a href="https://github.com/git/git" class="uri">https://github.com/git/git</a> is Git Source Code Mirror - This is a publish-only repository and all pull requests are ignored.<br>
https://git-scm.com/</p>
<p><strong>Git</strong> is a fast, scalable, distributed revision control system with an unusually rich command set that provides both high-level operations and full access to internals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>git_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/git/git.git'</span>, <span class="st">'git.git'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 754 ms</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'git.git'</span>] <span class="op">=</span> {</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'git.git'</span>,</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph_name'</span>: _repo_graph_name(<span class="st">'repos/git.git'</span>),</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/git/git.git'</span>,</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'homepage'</span>: <span class="st">'https://git-scm.com/'</span>,</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: git_graph,</span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_nodes'</span>: git_graph.number_of_nodes(),</span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_edges'</span>: git_graph.number_of_edges(),</span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'git.git'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>{'name': 'git.git',
 'graph_name': 'git-commit_graph',
 'url': 'https://github.com/git/git.git',
 'homepage': 'https://git-scm.com/',
 'graph': &lt;networkx.classes.digraph.DiGraph at 0x195f34bd640&gt;,
 'n_nodes': 63829,
 'n_edges': 79664}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>repo_name <span class="op">=</span> <span class="st">'git.git'</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has:'</span>.<span class="bu">format</span>(repo_name))</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>]))</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.6f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>] <span class="op">/</span> known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "git.git" project has:
- 63829 nodes / vertices / commits
- 79664 edges
- 1.248085 edge density, number of edges divided by number of nodes (vertices)
- 9 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 3 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
<p>Git.git repository on GitHub @ 01.01.2021: 61,475 commits, 5 branches</p>
</section>
<section id="gerrit-repository" class="level3">
<h3 class="anchored" data-anchor-id="gerrit-repository">Gerrit repository</h3>
<p><strong>Gerrit Code Review</strong> is a free, web-based team code collaboration tool. Software developers in a team can review each other’s modifications on their source code using a Web browser and approve or reject those changes. It integrates closely with Git, a distributed version control system.</p>
<p>https://www.gerritcodereview.com/</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>gerrit_graph <span class="op">=</span> commit_graph(<span class="st">'https://gerrit.googlesource.com/gerrit'</span>, <span class="st">'gerrit'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 402 ms</code></pre>
</div>
</div>
<p>Wall time: 1min 2s (first time), 0.4s (subsequent times)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'gerrit'</span>] <span class="op">=</span> {</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'gerrit'</span>,</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph_name'</span>: _repo_graph_name(<span class="st">'repos/gerrit'</span>),</span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://gerrit.googlesource.com/gerrit'</span>,</span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'homepage'</span>: <span class="st">'https://www.gerritcodereview.com/'</span>,</span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: gerrit_graph,</span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_nodes'</span>: gerrit_graph.number_of_nodes(),</span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_edges'</span>: gerrit_graph.number_of_edges(),</span>
<span id="cb90-9"><a href="#cb90-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb90-10"><a href="#cb90-10" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'gerrit'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 51 ms</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>{'name': 'gerrit',
 'graph_name': 'gerrit-commit_graph',
 'url': 'https://gerrit.googlesource.com/gerrit',
 'homepage': 'https://www.gerritcodereview.com/',
 'graph': &lt;networkx.classes.digraph.DiGraph at 0x196101db850&gt;,
 'n_nodes': 47687,
 'n_edges': 63944}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>repo_name <span class="op">=</span> <span class="st">'gerrit'</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has:'</span>.<span class="bu">format</span>(repo_name))</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>]))</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.6f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>] <span class="op">/</span> known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb93-10"><a href="#cb93-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "gerrit" project has:
- 47687 nodes / vertices / commits
- 63944 edges
- 1.340911 edge density, number of edges divided by number of nodes (vertices)
- 4 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 6 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
</section>
<section id="android-base-repository" class="level3">
<h3 class="anchored" data-anchor-id="android-base-repository">Android-base repository</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>android_graph <span class="op">=</span> commit_graph(<span class="st">'https://android.googlesource.com/platform/frameworks/base/'</span>, <span class="st">'android-base'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 9.33 s</code></pre>
</div>
</div>
<p>Wall time: 2min 9s (first time), 20.7 s (rescan), 9.33 s (subsequent runs)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co">#%%time</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="co">#!git clone --filter=tree:0 --no-checkout https://android.googlesource.com/platform/frameworks/base/ repos/android-base</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'android-base'</span>] <span class="op">=</span> {</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'android-base'</span>,</span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://android.googlesource.com/platform/frameworks/base/'</span>,</span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: android_graph,</span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_nodes'</span>: android_graph.number_of_nodes(),</span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_edges'</span>: android_graph.number_of_edges(),</span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb98-8"><a href="#cb98-8" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'android-base'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>{'name': 'android-base',
 'url': 'https://android.googlesource.com/platform/frameworks/base/',
 'graph': &lt;networkx.classes.digraph.DiGraph at 0x1961516dc10&gt;,
 'n_nodes': 559423,
 'n_edges': 984070}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>repo_name <span class="op">=</span> <span class="st">'android-base'</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has:'</span>.<span class="bu">format</span>(repo_name))</span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>]))</span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.6f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>] <span class="op">/</span> known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb100-7"><a href="#cb100-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb100-8"><a href="#cb100-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb100-9"><a href="#cb100-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb100-10"><a href="#cb100-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "android-base" project has:
- 559423 nodes / vertices / commits
- 984070 edges
- 1.759080 edge density, number of edges divided by number of nodes (vertices)
- 3 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 1 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
</section>
<section id="chromium-repository" class="level3">
<h3 class="anchored" data-anchor-id="chromium-repository">Chromium repository</h3>
<p><strong>Chromium</strong> is an open-source browser project that aims to build a safer, faster, and more stable way for all users to experience the web.</p>
<p>The project’s web site is https://www.chromium.org.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>chromium_graph <span class="op">=</span> commit_graph(<span class="st">'https://chromium.googlesource.com/chromium/src'</span>, <span class="st">'chromium'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 14.1 s</code></pre>
</div>
</div>
<p>Wall time: 39min 52s (first time, possibly failed), rescan: 39.3 s, subsequent runs: 14.1 s</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'chromium'</span>] <span class="op">=</span> {</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'chromium'</span>,</span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://chromium.googlesource.com/chromium/src'</span>,</span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'homepage'</span>: <span class="st">'https://www.chromium.org'</span>,</span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: chromium_graph,</span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_nodes'</span>: chromium_graph.number_of_nodes(),</span>
<span id="cb104-7"><a href="#cb104-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_edges'</span>: chromium_graph.number_of_edges(),</span>
<span id="cb104-8"><a href="#cb104-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb104-9"><a href="#cb104-9" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'chromium'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>{'name': 'chromium',
 'url': 'https://chromium.googlesource.com/chromium/src',
 'homepage': 'https://www.chromium.org',
 'graph': &lt;networkx.classes.digraph.DiGraph at 0x196101db7c0&gt;,
 'n_nodes': 961204,
 'n_edges': 961263}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>repo_name <span class="op">=</span> <span class="st">'chromium'</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has:'</span>.<span class="bu">format</span>(repo_name))</span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb106-4"><a href="#cb106-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>]))</span>
<span id="cb106-5"><a href="#cb106-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.6f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb106-6"><a href="#cb106-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>] <span class="op">/</span> known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb106-7"><a href="#cb106-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb106-8"><a href="#cb106-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb106-9"><a href="#cb106-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb106-10"><a href="#cb106-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "chromium" project has:
- 961204 nodes / vertices / commits
- 961263 edges
- 1.000061 edge density, number of edges divided by number of nodes (vertices)
- 3 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 1 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
</section>
</section>
<section id="slides-unused-repositories" class="level2">
<h2 class="anchored" data-anchor-id="slides-unused-repositories">Slides (unused repositories)</h2>
<p>These are the repositories (not present among the repositories above) that were considered for inclusion in “<a href="https://drive.google.com/open?id=1psMBVfcRHcZeJ7AewGpdoymrEfFVdXoK" title="Graph operations in Git version control system (PDF)"><em>Graph operations in Git version control system</em></a>”, and are presented as comments in the <code>*.tex</code> sources.</p>
<section id="llvm-repository" class="level3">
<h3 class="anchored" data-anchor-id="llvm-repository">LLVM repository</h3>
<p>The LLVM Compiler Infrastructure<br>
https://llvm.org/</p>
<p>The LLVM Project is a collection of modular and reusable compiler and toolchain technologies. Despite its name, LLVM has little to do with traditional virtual machines. The name “LLVM” itself is not an acronym; it is the full name of the project.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>llvm_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/llvm/llvm-project.git'</span>, <span class="st">'llvm'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 3.53 s</code></pre>
</div>
</div>
<p>Wall time: 33.5 s (first time), 3.53 s (subsequent run)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'llvm'</span>] <span class="op">=</span> {</span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'llvm'</span>,</span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/llvm/llvm-project.git'</span>,</span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'homepage'</span>: <span class="st">'https://llvm.org/'</span>,</span>
<span id="cb110-5"><a href="#cb110-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: llvm_graph,</span>
<span id="cb110-6"><a href="#cb110-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_nodes'</span>: llvm_graph.number_of_nodes(),</span>
<span id="cb110-7"><a href="#cb110-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_edges'</span>: llvm_graph.number_of_edges(),</span>
<span id="cb110-8"><a href="#cb110-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb110-9"><a href="#cb110-9" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'llvm'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>{'name': 'llvm',
 'url': 'https://github.com/llvm/llvm-project.git',
 'homepage': 'https://llvm.org/',
 'graph': &lt;networkx.classes.digraph.DiGraph at 0x1969020a430&gt;,
 'n_nodes': 381471,
 'n_edges': 381486}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>repo_name <span class="op">=</span> <span class="st">'llvm'</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has:'</span>.<span class="bu">format</span>(repo_name))</span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>]))</span>
<span id="cb112-5"><a href="#cb112-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.6f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb112-6"><a href="#cb112-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>] <span class="op">/</span> known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb112-7"><a href="#cb112-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb112-8"><a href="#cb112-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb112-9"><a href="#cb112-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb112-10"><a href="#cb112-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "llvm" project has:
- 381471 nodes / vertices / commits
- 381486 edges
- 1.000039 edge density, number of edges divided by number of nodes (vertices)
- 3 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 40 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
<p>The LLVM repository on GitHub @ 01.01.2021: 375,962 commits, 42 branches</p>
</section>
<section id="gcc-repository" class="level3">
<h3 class="anchored" data-anchor-id="gcc-repository">GCC repository</h3>
<p>GCC, the GNU Compiler Collection<br>
https://gcc.gnu.org/</p>
<p>The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Ada, Go, and D, as well as libraries for these languages (libstdc++,…). GCC was originally written as the compiler for the GNU operating system.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>gcc_graph <span class="op">=</span> commit_graph(<span class="st">'https://gcc.gnu.org/git/gcc.git'</span>, <span class="st">'gcc'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 2.15 s</code></pre>
</div>
</div>
<p>Wall time: 13min 48s (first time), 2.15s (subsequent runs)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'gcc'</span>] <span class="op">=</span> {</span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'gcc'</span>,</span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://gcc.gnu.org/git/gcc.git'</span>,</span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'homepage'</span>: <span class="st">'https://gcc.gnu.org/'</span>,</span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: gcc_graph,</span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_nodes'</span>: gcc_graph.number_of_nodes(),</span>
<span id="cb116-7"><a href="#cb116-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_edges'</span>: gcc_graph.number_of_edges(),</span>
<span id="cb116-8"><a href="#cb116-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb116-9"><a href="#cb116-9" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'gcc'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>{'name': 'gcc',
 'url': 'https://gcc.gnu.org/git/gcc.git',
 'homepage': 'https://gcc.gnu.org/',
 'graph': &lt;networkx.classes.digraph.DiGraph at 0x1969020a250&gt;,
 'n_nodes': 241243,
 'n_edges': 242024}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>repo_name <span class="op">=</span> <span class="st">'gcc'</span></span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has:'</span>.<span class="bu">format</span>(repo_name))</span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>]))</span>
<span id="cb118-5"><a href="#cb118-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.6f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb118-6"><a href="#cb118-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>] <span class="op">/</span> known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb118-7"><a href="#cb118-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb118-8"><a href="#cb118-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb118-9"><a href="#cb118-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb118-10"><a href="#cb118-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "gcc" project has:
- 241243 nodes / vertices / commits
- 242024 edges
- 1.003237 edge density, number of edges divided by number of nodes (vertices)
- 1 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 45 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
</section>
<section id="homebrew-repository" class="level3">
<h3 class="anchored" data-anchor-id="homebrew-repository">Homebrew repository</h3>
<p>Homebrew – The Missing Package Manager for macOS (or Linux)<br>
https://brew.sh/</p>
<p><strong>Homebrew</strong> is a free and open-source software package management system that simplifies the installation of software on Apple’s macOS operating system and Linux. The name is intended to suggest the idea of building software on the Mac depending on the user’s taste.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>brew_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/Homebrew/brew.git'</span>, <span class="st">'homebrew'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 452 ms</code></pre>
</div>
</div>
<p>Wall time: 28 s (first time), 452 ms (subsequent times)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'homebrew'</span>] <span class="op">=</span> {</span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'homebrew'</span>,</span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/Homebrew/brew.git'</span>,</span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'homepage'</span>: <span class="st">'https://brew.sh/'</span>,</span>
<span id="cb122-5"><a href="#cb122-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: brew_graph,</span>
<span id="cb122-6"><a href="#cb122-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_nodes'</span>: brew_graph.number_of_nodes(),</span>
<span id="cb122-7"><a href="#cb122-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_edges'</span>: brew_graph.number_of_edges(),</span>
<span id="cb122-8"><a href="#cb122-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb122-9"><a href="#cb122-9" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'homebrew'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>{'name': 'homebrew',
 'url': 'https://github.com/Homebrew/brew.git',
 'homepage': 'https://brew.sh/',
 'graph': &lt;networkx.classes.digraph.DiGraph at 0x1961516dbb0&gt;,
 'n_nodes': 25286,
 'n_edges': 30956}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>repo_name <span class="op">=</span> <span class="st">'homebrew'</span></span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has:'</span>.<span class="bu">format</span>(repo_name))</span>
<span id="cb124-3"><a href="#cb124-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb124-4"><a href="#cb124-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>]))</span>
<span id="cb124-5"><a href="#cb124-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.6f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb124-6"><a href="#cb124-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>] <span class="op">/</span> known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb124-7"><a href="#cb124-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb124-8"><a href="#cb124-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb124-9"><a href="#cb124-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb124-10"><a href="#cb124-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "homebrew" project has:
- 25286 nodes / vertices / commits
- 30956 edges
- 1.224235 edge density, number of edges divided by number of nodes (vertices)
- 2 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 4 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
<p>Homebrew (brew) repository on GitHub @ 05.01.2021: 25,281 commits, 4 branches</p>
</section>
<section id="ruby-on-rails-repository" class="level3">
<h3 class="anchored" data-anchor-id="ruby-on-rails-repository">Ruby on Rails repository</h3>
<p>Ruby on Rails | A web-application framework that includes everything needed to create database-backed web applications according to the Model-View-Controller (MVC) pattern.<br>
https://rubyonrails.org/</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>rails_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/rails/rails.git'</span>, <span class="st">'rails'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 776 ms</code></pre>
</div>
</div>
<p>Wall time: 57.1 s (first time), 776 ms (subsequent times)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'rails'</span>] <span class="op">=</span> {</span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'rails'</span>,</span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/rails/rails.git'</span>,</span>
<span id="cb128-4"><a href="#cb128-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'homepage'</span>: <span class="st">'https://rubyonrails.org/'</span>,</span>
<span id="cb128-5"><a href="#cb128-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: rails_graph,</span>
<span id="cb128-6"><a href="#cb128-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_nodes'</span>: rails_graph.number_of_nodes(),</span>
<span id="cb128-7"><a href="#cb128-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_edges'</span>: rails_graph.number_of_edges(),</span>
<span id="cb128-8"><a href="#cb128-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb128-9"><a href="#cb128-9" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'rails'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>{'name': 'rails',
 'url': 'https://github.com/rails/rails.git',
 'homepage': 'https://rubyonrails.org/',
 'graph': &lt;networkx.classes.digraph.DiGraph at 0x195f34bd460&gt;,
 'n_nodes': 92577,
 'n_edges': 111930}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>repo_name <span class="op">=</span> <span class="st">'rails'</span></span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has:'</span>.<span class="bu">format</span>(repo_name))</span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb130-4"><a href="#cb130-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>]))</span>
<span id="cb130-5"><a href="#cb130-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.6f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb130-6"><a href="#cb130-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>] <span class="op">/</span> known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb130-7"><a href="#cb130-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb130-8"><a href="#cb130-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb130-9"><a href="#cb130-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb130-10"><a href="#cb130-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "rails" project has:
- 92577 nodes / vertices / commits
- 111930 edges
- 1.209048 edge density, number of edges divided by number of nodes (vertices)
- 7 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 48 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
<p>Ruby on Rails repository on GitHub @ 05.01.2021: 78,831 commits, 52 branches</p>
</section>
</section>
<section id="github-blog-post-on-cloning-behavior" class="level2">
<h2 class="anchored" data-anchor-id="github-blog-post-on-cloning-behavior">GitHub Blog post on cloning behavior</h2>
<p>“<em>Git clone: a data-driven study on cloning behaviors</em>”<br>
Solmaz Abbaspoursani, December 22, 2020<br>
https://github.blog/2020-12-22-git-clone-a-data-driven-study-on-cloning-behaviors/</p>
<section id="jquery-repository" class="level3">
<h3 class="anchored" data-anchor-id="jquery-repository">jQuery repository</h3>
<p><strong>jQuery</strong> is a fast, small, and feature-rich JavaScript library. It makes things like HTML document traversal and manipulation, event handling, animation, and Ajax much simpler with an easy-to-use API that works across a multitude of browsers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a>jquery_graph <span class="op">=</span> commit_graph(<span class="st">'https://github.com/jquery/jquery.git'</span>, <span class="st">'jquery'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Wall time: 69 ms</code></pre>
</div>
</div>
<p>Wall time: 12.7 s (first time), 0.07 s (subsequent times)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'jquery'</span>] <span class="op">=</span> {</span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'name'</span>: <span class="st">'jquery'</span>,</span>
<span id="cb134-3"><a href="#cb134-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'url'</span>: <span class="st">'https://github.com/jquery/jquery.git'</span>,</span>
<span id="cb134-4"><a href="#cb134-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'homepage'</span>: <span class="st">'https://jquery.com/'</span>,</span>
<span id="cb134-5"><a href="#cb134-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'graph'</span>: jquery_graph,</span>
<span id="cb134-6"><a href="#cb134-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_nodes'</span>: jquery_graph.number_of_nodes(),</span>
<span id="cb134-7"><a href="#cb134-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_edges'</span>: jquery_graph.number_of_edges(),</span>
<span id="cb134-8"><a href="#cb134-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb134-9"><a href="#cb134-9" aria-hidden="true" tabindex="-1"></a>known_repo[<span class="st">'jquery'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>{'name': 'jquery',
 'url': 'https://github.com/jquery/jquery.git',
 'homepage': 'https://jquery.com/',
 'graph': &lt;networkx.classes.digraph.DiGraph at 0x196ca968820&gt;,
 'n_nodes': 7741,
 'n_edges': 7990}</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a>repo_name <span class="op">=</span> <span class="st">'jquery'</span></span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'commit graph of "</span><span class="sc">{}</span><span class="st">" project has:'</span>.<span class="bu">format</span>(repo_name))</span>
<span id="cb136-3"><a href="#cb136-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> nodes / vertices / commits'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb136-4"><a href="#cb136-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> edges'</span>.<span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>]))</span>
<span id="cb136-5"><a href="#cb136-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{:.6f}</span><span class="st"> edge density, number of edges divided by number of nodes (vertices)'</span>.</span>
<span id="cb136-6"><a href="#cb136-6" aria-hidden="true" tabindex="-1"></a>      <span class="bu">format</span>(known_repo[repo_name][<span class="st">'n_edges'</span>] <span class="op">/</span> known_repo[repo_name][<span class="st">'n_nodes'</span>]))</span>
<span id="cb136-7"><a href="#cb136-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sinks / leafs / roots in git parlance, nodes with no outgoing edges'</span>.</span>
<span id="cb136-8"><a href="#cb136-8" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].out_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span>
<span id="cb136-9"><a href="#cb136-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'- </span><span class="sc">{}</span><span class="st"> sources / roots / heads in git parlance, nodes with no incoming edge'</span>.</span>
<span id="cb136-10"><a href="#cb136-10" aria-hidden="true" tabindex="-1"></a>     <span class="bu">format</span>(<span class="bu">len</span>([n <span class="cf">for</span> n <span class="kw">in</span> known_repo[repo_name][<span class="st">'graph'</span>] <span class="cf">if</span> known_repo[repo_name][<span class="st">'graph'</span>].in_degree(n) <span class="op">==</span> <span class="dv">0</span>])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>commit graph of "jquery" project has:
- 7741 nodes / vertices / commits
- 7990 edges
- 1.032166 edge density, number of edges divided by number of nodes (vertices)
- 1 sinks / leafs / roots in git parlance, nodes with no outgoing edges
- 4 sources / roots / heads in git parlance, nodes with no incoming edge</code></pre>
</div>
</div>
<p>jQuery repository on GitHub on 05.01.2021: 6,519 commits, 4 branches</p>
</section>
</section>
<section id="other-possibilities" class="level2">
<h2 class="anchored" data-anchor-id="other-possibilities">Other possibilities</h2>
<p>Browsing through OpenHub and GitHub (neither of which provides a search mechanism or a sort order for the number of commits), the following repositories may be considered for inclusion:</p>
<ul class="task-list">
<li><input type="checkbox">OpenBSD, with around 650,000 commits</li>
<li><input type="checkbox">FreeBSD, with around 250,000 commits</li>
<li><input type="checkbox">LibreOffice, with around 500,000 commits</li>
<li><input type="checkbox">Mozilla Firefox, with around 740,000 commits</li>
<li><input type="checkbox">GNU Emacs, with around 150,000 commits</li>
</ul>
<p>Another good source for large repositories might be the Git Merge 2017 talk “<a href="https://www.youtube.com/watch?v=-ZNKR9wFe8o">Top Ten Worst Repositories to host on GitHub - Git Merge 2017</a>” (on YouTube)</p>
<ul>
<li>Kubernetes (large amoun of pull requests, around 100,000 commits)</li>
<li>CocoaPods/Specs (with around 550,000 commits, automatic)</li>
<li>octocats/Spoon-Knife (3 commits, 5k+ pull requests, 115k forks)</li>
<li>IntelliJ IDEA Community Edition (around 300,000 commits, around 700 tags - was 45k tags)</li>
<li>EnkiDevs/commit (around 150,000 commits, 26k individual authors, leaderboard, archived)</li>
</ul>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>Imports for data analysis</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb138-2"><a href="#cb138-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb138-3"><a href="#cb138-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, repo <span class="kw">in</span> known_repo.items():</span>
<span id="cb139-2"><a href="#cb139-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'... processing </span><span class="sc">{}</span><span class="st">'</span>.<span class="bu">format</span>(name))</span>
<span id="cb139-3"><a href="#cb139-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="st">'n_nodes'</span> <span class="kw">not</span> <span class="kw">in</span> repo:</span>
<span id="cb139-4"><a href="#cb139-4" aria-hidden="true" tabindex="-1"></a>        repo[<span class="st">'n_nodes'</span>] <span class="op">=</span> repo[<span class="st">'graph'</span>].number_of_nodes()</span>
<span id="cb139-5"><a href="#cb139-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="st">'n_edges'</span> <span class="kw">not</span> <span class="kw">in</span> repo:</span>
<span id="cb139-6"><a href="#cb139-6" aria-hidden="true" tabindex="-1"></a>        repo[<span class="st">'n_edges'</span>] <span class="op">=</span> repo[<span class="st">'graph'</span>].number_of_edges()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>... processing curl
... processing electron
... processing ffmpeg
... processing jgit
... processing julia
... processing kotlin
... processing linux
... processing odoo
... processing openssl
... processing swift
... processing tensorflow
... processing typescript
... processing git.git
... processing gerrit
... processing android-base
... processing chromium
... processing llvm
... processing gcc
... processing homebrew
... processing rails</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a>known_repo_df <span class="op">=</span> pd.DataFrame.from_dict(known_repo, orient<span class="op">=</span><span class="st">'index'</span>,</span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a>                                       columns<span class="op">=</span>[<span class="st">'url'</span>, <span class="st">'n_nodes'</span>, <span class="st">'n_edges'</span>]).astype({<span class="st">'url'</span>: <span class="st">'str'</span>})</span>
<span id="cb141-3"><a href="#cb141-3" aria-hidden="true" tabindex="-1"></a>known_repo_df[<span class="st">'n_edges / n_nodes'</span>] <span class="op">=</span> known_repo_df[<span class="st">'n_edges'</span>] <span class="op">/</span> known_repo_df[<span class="st">'n_nodes'</span>]</span>
<span id="cb141-4"><a href="#cb141-4" aria-hidden="true" tabindex="-1"></a>known_repo_df.sort_values(<span class="st">'n_nodes'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">url</th>
<th data-quarto-table-cell-role="th">n_nodes</th>
<th data-quarto-table-cell-role="th">n_edges</th>
<th data-quarto-table-cell-role="th">n_edges / n_nodes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">jquery</td>
<td>https://github.com/jquery/jquery.git</td>
<td>7741</td>
<td>7990</td>
<td>1.032166</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">jgit</td>
<td>https://github.com/eclipse/jgit.git</td>
<td>8173</td>
<td>9853</td>
<td>1.205555</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">homebrew</td>
<td>https://github.com/Homebrew/brew.git</td>
<td>25286</td>
<td>30956</td>
<td>1.224235</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">curl</td>
<td>https://github.com/curl/curl</td>
<td>26609</td>
<td>26631</td>
<td>1.000827</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">electron</td>
<td>https://github.com/electron/electron.git</td>
<td>29956</td>
<td>34167</td>
<td>1.140573</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">typescript</td>
<td>https://github.com/microsoft/TypeScript.git</td>
<td>35486</td>
<td>43895</td>
<td>1.236967</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">openssl</td>
<td>https://github.com/openssl/openssl.git</td>
<td>42818</td>
<td>42997</td>
<td>1.004180</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">gerrit</td>
<td>https://gerrit.googlesource.com/gerrit</td>
<td>47687</td>
<td>63944</td>
<td>1.340911</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">julia</td>
<td>https://github.com/JuliaLang/julia.git</td>
<td>56048</td>
<td>67547</td>
<td>1.205163</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">git.git</td>
<td>https://github.com/git/git.git</td>
<td>63829</td>
<td>79664</td>
<td>1.248085</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">rails</td>
<td>https://github.com/rails/rails.git</td>
<td>92577</td>
<td>111930</td>
<td>1.209048</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">tensorflow</td>
<td>https://github.com/tensorflow/tensorflow.git</td>
<td>105236</td>
<td>115687</td>
<td>1.099310</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">kotlin</td>
<td>https://github.com/JetBrains/kotlin.git</td>
<td>117495</td>
<td>119013</td>
<td>1.012920</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ffmpeg</td>
<td>https://github.com/FFmpeg/FFmpeg.git</td>
<td>120583</td>
<td>130606</td>
<td>1.083121</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">swift</td>
<td>https://github.com/apple/swift.git</td>
<td>132444</td>
<td>176028</td>
<td>1.329075</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">odoo</td>
<td>https://github.com/odoo/odoo.git</td>
<td>158324</td>
<td>184403</td>
<td>1.164719</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">gcc</td>
<td>https://gcc.gnu.org/git/gcc.git</td>
<td>241243</td>
<td>242024</td>
<td>1.003237</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">llvm</td>
<td>https://github.com/llvm/llvm-project.git</td>
<td>381471</td>
<td>381486</td>
<td>1.000039</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">android-base</td>
<td>https://android.googlesource.com/platform/fram...</td>
<td>559423</td>
<td>984070</td>
<td>1.759080</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">chromium</td>
<td>https://chromium.googlesource.com/chromium/src</td>
<td>961204</td>
<td>961263</td>
<td>1.000061</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">linux</td>
<td>https://github.com/torvalds/linux.git</td>
<td>982030</td>
<td>1061095</td>
<td>1.080512</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a>known_repo_df.dtypes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<pre><code>url                   object
n_nodes                int64
n_edges                int64
n_edges / n_nodes    float64
dtype: object</code></pre>
</div>
</div>
<p>Makit it so that the labels do not overlap.</p>
<p>https://support.sisense.com/hc/en-us/community/posts/360037908374-Getting-Around-Overlapping-Data-Labels-With-Python<br>
https://github.com/Phlya/adjustText/</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb144"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="co"># source: https://stackoverflow.com/questions/8850142/matplotlib-overlapping-annotations</span></span>
<span id="cb144-2"><a href="#cb144-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_text_positions(x_data, y_data, txt_width, txt_height):</span>
<span id="cb144-3"><a href="#cb144-3" aria-hidden="true" tabindex="-1"></a>    a <span class="op">=</span> <span class="bu">zip</span>(y_data, x_data)</span>
<span id="cb144-4"><a href="#cb144-4" aria-hidden="true" tabindex="-1"></a>    text_positions <span class="op">=</span> y_data.copy()</span>
<span id="cb144-5"><a href="#cb144-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> index, (y, x) <span class="kw">in</span> <span class="bu">enumerate</span>(a):</span>
<span id="cb144-6"><a href="#cb144-6" aria-hidden="true" tabindex="-1"></a>        local_text_positions <span class="op">=</span> [i <span class="cf">for</span> i <span class="kw">in</span> a <span class="cf">if</span> i[<span class="dv">0</span>] <span class="op">&gt;</span> (y <span class="op">-</span> txt_height)</span>
<span id="cb144-7"><a href="#cb144-7" aria-hidden="true" tabindex="-1"></a>                                <span class="kw">and</span> (<span class="bu">abs</span>(i[<span class="dv">1</span>] <span class="op">-</span> x) <span class="op">&lt;</span> txt_width <span class="op">*</span> <span class="dv">2</span>) <span class="kw">and</span> i <span class="op">!=</span> (y,x)]</span>
<span id="cb144-8"><a href="#cb144-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> local_text_positions:</span>
<span id="cb144-9"><a href="#cb144-9" aria-hidden="true" tabindex="-1"></a>            sorted_ltp <span class="op">=</span> <span class="bu">sorted</span>(local_text_positions)</span>
<span id="cb144-10"><a href="#cb144-10" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="bu">abs</span>(sorted_ltp[<span class="dv">0</span>][<span class="dv">0</span>] <span class="op">-</span> y) <span class="op">&lt;</span> txt_height: <span class="co">#True == collision</span></span>
<span id="cb144-11"><a href="#cb144-11" aria-hidden="true" tabindex="-1"></a>                differ <span class="op">=</span> np.diff(sorted_ltp, axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb144-12"><a href="#cb144-12" aria-hidden="true" tabindex="-1"></a>                a[index] <span class="op">=</span> (sorted_ltp[<span class="op">-</span><span class="dv">1</span>][<span class="dv">0</span>] <span class="op">+</span> txt_height, a[index][<span class="dv">1</span>])</span>
<span id="cb144-13"><a href="#cb144-13" aria-hidden="true" tabindex="-1"></a>                text_positions[index] <span class="op">=</span> sorted_ltp[<span class="op">-</span><span class="dv">1</span>][<span class="dv">0</span>] <span class="op">+</span> txt_height</span>
<span id="cb144-14"><a href="#cb144-14" aria-hidden="true" tabindex="-1"></a>                <span class="cf">for</span> k, (j, m) <span class="kw">in</span> <span class="bu">enumerate</span>(differ):</span>
<span id="cb144-15"><a href="#cb144-15" aria-hidden="true" tabindex="-1"></a>                    <span class="co">#j is the vertical distance between words</span></span>
<span id="cb144-16"><a href="#cb144-16" aria-hidden="true" tabindex="-1"></a>                    <span class="cf">if</span> j <span class="op">&gt;</span> txt_height <span class="op">*</span> <span class="fl">1.5</span>: <span class="co">#if True then room to fit a word in</span></span>
<span id="cb144-17"><a href="#cb144-17" aria-hidden="true" tabindex="-1"></a>                        a[index] <span class="op">=</span> (sorted_ltp[k][<span class="dv">0</span>] <span class="op">+</span> txt_height, a[index][<span class="dv">1</span>])</span>
<span id="cb144-18"><a href="#cb144-18" aria-hidden="true" tabindex="-1"></a>                        text_positions[index] <span class="op">=</span> sorted_ltp[k][<span class="dv">0</span>] <span class="op">+</span> txt_height</span>
<span id="cb144-19"><a href="#cb144-19" aria-hidden="true" tabindex="-1"></a>                        <span class="cf">break</span></span>
<span id="cb144-20"><a href="#cb144-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> text_positions</span>
<span id="cb144-21"><a href="#cb144-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb144-22"><a href="#cb144-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb144-23"><a href="#cb144-23" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> text_plotter(x_data, y_data, text_positions, axis,txt_width,txt_height):</span>
<span id="cb144-24"><a href="#cb144-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> x,y,t <span class="kw">in</span> <span class="bu">zip</span>(x_data, y_data, text_positions):</span>
<span id="cb144-25"><a href="#cb144-25" aria-hidden="true" tabindex="-1"></a>        axis.text(x <span class="op">-</span> <span class="fl">.03</span>, <span class="fl">1.02</span><span class="op">*</span>t, <span class="st">'</span><span class="sc">%d</span><span class="st">'</span><span class="op">%</span><span class="bu">int</span>(y),rotation<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">'blue'</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb144-26"><a href="#cb144-26" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> y <span class="op">!=</span> t:</span>
<span id="cb144-27"><a href="#cb144-27" aria-hidden="true" tabindex="-1"></a>            axis.arrow(x, t<span class="op">+</span><span class="dv">20</span>,<span class="dv">0</span>,y<span class="op">-</span>t, color<span class="op">=</span><span class="st">'blue'</span>,alpha<span class="op">=</span><span class="fl">0.2</span>, width<span class="op">=</span>txt_width<span class="op">*</span><span class="fl">0.0</span>,</span>
<span id="cb144-28"><a href="#cb144-28" aria-hidden="true" tabindex="-1"></a>                       head_width<span class="op">=</span><span class="fl">.02</span>, head_length<span class="op">=</span>txt_height<span class="op">*</span><span class="fl">0.5</span>,</span>
<span id="cb144-29"><a href="#cb144-29" aria-hidden="true" tabindex="-1"></a>                       zorder<span class="op">=</span><span class="dv">0</span>,length_includes_head<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">18</span>, <span class="dv">10</span>))</span>
<span id="cb145-3"><a href="#cb145-3" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> known_repo_df.plot.scatter(x<span class="op">=</span><span class="st">'n_nodes'</span>, y<span class="op">=</span><span class="st">'n_edges'</span>,</span>
<span id="cb145-4"><a href="#cb145-4" aria-hidden="true" tabindex="-1"></a>                                logx<span class="op">=</span><span class="va">True</span>, logy<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb145-5"><a href="#cb145-5" aria-hidden="true" tabindex="-1"></a>                                grid<span class="op">=</span><span class="va">True</span>, ax<span class="op">=</span>ax,</span>
<span id="cb145-6"><a href="#cb145-6" aria-hidden="true" tabindex="-1"></a>                                title<span class="op">=</span><span class="st">'Commit graphs of Git repositories'</span>)</span>
<span id="cb145-7"><a href="#cb145-7" aria-hidden="true" tabindex="-1"></a><span class="co"># line</span></span>
<span id="cb145-8"><a href="#cb145-8" aria-hidden="true" tabindex="-1"></a>ee <span class="op">=</span> np.geomspace(<span class="dv">5000</span>,<span class="dv">1100000</span>,num<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb145-9"><a href="#cb145-9" aria-hidden="true" tabindex="-1"></a>ax.plot(ee, ee, <span class="st">'-.'</span>, label<span class="op">=</span><span class="st">'nodes == edges'</span>, c<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb145-10"><a href="#cb145-10" aria-hidden="true" tabindex="-1"></a><span class="co"># parameters</span></span>
<span id="cb145-11"><a href="#cb145-11" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(left  <span class="op">=</span><span class="fl">5e3</span>)</span>
<span id="cb145-12"><a href="#cb145-12" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(bottom<span class="op">=</span><span class="fl">5e3</span>)</span>
<span id="cb145-13"><a href="#cb145-13" aria-hidden="true" tabindex="-1"></a><span class="co">#plt.legend(loc='upper left')</span></span>
<span id="cb145-14"><a href="#cb145-14" aria-hidden="true" tabindex="-1"></a><span class="co"># labels</span></span>
<span id="cb145-15"><a href="#cb145-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row <span class="kw">in</span> known_repo_df.itertuples():</span>
<span id="cb145-16"><a href="#cb145-16" aria-hidden="true" tabindex="-1"></a>    ax.annotate(row[<span class="dv">0</span>], xy<span class="op">=</span>(row.n_nodes, row.n_edges),</span>
<span id="cb145-17"><a href="#cb145-17" aria-hidden="true" tabindex="-1"></a>                xytext<span class="op">=</span>(<span class="op">-</span><span class="dv">3</span>,<span class="dv">2</span>), textcoords<span class="op">=</span><span class="st">'offset points'</span>, horizontalalignment<span class="op">=</span><span class="st">'right'</span>,</span>
<span id="cb145-18"><a href="#cb145-18" aria-hidden="true" tabindex="-1"></a>                family<span class="op">=</span><span class="st">'sans-serif'</span>, fontsize<span class="op">=</span><span class="dv">9</span>, color<span class="op">=</span><span class="st">'darkslategrey'</span>)</span>
<span id="cb145-19"><a href="#cb145-19" aria-hidden="true" tabindex="-1"></a><span class="co"># show</span></span>
<span id="cb145-20"><a href="#cb145-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="12_repos_files/figure-html/cell-78-output-1.png" class="img-fluid"></p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>