# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"crown_DAG": "03_example_graphs.ipynb",
         "small_DAG_FELINE": "03_example_graphs.ipynb",
         "tree_DAG": "03_example_graphs.ipynb",
         "levels_DAG_FELINE": "03_example_graphs.ipynb",
         "RCH_graph": "03_example_graphs.ipynb",
         "commit_graph": "03_example_graphs.ipynb"}

modules = ["example_graphs.py"]

doc_url = "https://jnareb.github.io/git-commit-graph-ext/"

git_url = "https://github.com/jnareb/git-commit-graph-ext/tree/master/"

def custom_doc_links(name): return None
