# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"crown_DAG": "03_example_graphs.ipynb",
         "small_DAG_FELINE": "03_example_graphs.ipynb",
         "tree_DAG": "03_example_graphs.ipynb",
         "levels_DAG_FELINE": "03_example_graphs.ipynb",
         "RCH_graph": "03_example_graphs.ipynb",
         "commit_graph": "03_example_graphs.ipynb",
         "find_levels": "06_levels.ipynb",
         "find_dfs_spanning": "07_interval_labels.ipynb",
         "find_dfs_intervals": "07_interval_labels.ipynb",
         "find_dfs_intervals_extra": "07_interval_labels.ipynb",
         "generic_is_reachable": "08_reach.ipynb",
         "generic_is_reachable_dfs": "08_reach.ipynb",
         "reachable_positive_cut": "08_reach.ipynb",
         "reachable_negative_cut": "08_reach.ipynb",
         "walk_spanning": "08_reach.ipynb",
         "generic_is_reachable_bfs": "08_reach.ipynb"}

modules = ["example_graphs.py",
           "labelling/levels.py",
           "labelling/dfs_intervals.py",
           "reachability.py"]

doc_url = "https://jnareb.github.io/git-commit-graph-ext/"

git_url = "https://github.com/jnareb/git-commit-graph-ext/tree/master/"

def custom_doc_links(name): return None
