# AUTOGENERATED! DO NOT EDIT! File to edit: 03_example_graphs.ipynb (unless otherwise specified).

__all__ = ['crown_DAG', 'small_DAG_FELINE', 'tree_DAG']

# Cell
import networkx as nx
import matplotlib.pyplot as plt


# Cell
def crown_DAG():
    """Returns crown DAG known as S_3^0 graph

    Returns
    -------
    graph : networkx.DiGraph
        Crown DAG also known as S_3^0 directed graph
    """
    DG=nx.DiGraph()
    DG.add_nodes_from([1,2,3,4,'u','v'])
    DG.add_edges_from([(1,2),(3,4),(1,'v'),(3,'v'),('u',2),('u',4)])
    return DG


# Cell
def small_DAG_FELINE():
    """Create small DAG (example in Figure 2 in FELINE paper)

    Returns
    -------
    graph : networkx.DiGraph
        Small DAG (example in Figure 2 in FELINE paper)
    """
    sd=nx.DiGraph()
    sd.add_nodes_from([chr(c) for c in range(ord('a'),ord('h')+1)])
    sd.add_edges_from([('a','c'),('a','d'),('a','e'),('b','f'),('b','g'),('c','h'),('e','h'),('f','h')])
    return sd


# Cell
def tree_DAG():
    """Create tree DAG ('didactic example' in Figure 6 in FELINE paper)

    The created tree graph has a single source node with out-degree of 3,
    its 3 out-neighbours have out-degrees, respectively, of 2, 1 and 2.
    Out-neighbours of those nodes are sink nodes with out-degree of 0.
    The tree has maximum level of 3.

    Below there is ASCII-art rendering of this graph; edges point downward

                                'a'
                              __/|\__
                             /   |   \
                           'b'  'c'  'd'
                           / \   |   / \
                          /  |   |   |  \
                        'e' 'f' 'g' 'h' 'i'

    Returns
    -------
    graph : networkx.DiGraph
        Tree DAG (example in Figure 6 in FELINE paper)
    """
    de=nx.DiGraph()
    de.add_nodes_from([chr(c) for c in range(ord('a'),ord('i')+1)])
    de.add_edges_from([('a','b'),('a','c'),('a','d'),
                       ('b','e'),('b','f'),
                       ('c','g'),
                       ('d','h'),('d','i')])
    return de